export const ListTag =[
    {id:1, nameTag:'Game'},
    {id:2, nameTag:'Digitalpainting'},
    {id:3, nameTag:'Anime'},
    {id:4, nameTag:'Fairy'},
    {id:5, nameTag:'Cute'},
    {id:6, nameTag:'SMagicalrealism'},
    {id:7, nameTag:'Animal'},
    {id:8, nameTag:'FMagicalspirit'},
    {id:9, nameTag:'Blue'},
    {id:10, nameTag:'Pink'},
    {id:11, nameTag:'Fantasyartwork'},
    {id:12, nameTag:'Fan art'},
    {id:13, nameTag:'Cat'},
    {id:14, nameTag:'Drink'},
    {id:15, nameTag:'Fantasyart'},
    {id:16, nameTag:'Female character'},
    {id:17, nameTag:'Digitalillustration '},
    {id:18, nameTag:'Background'},
    {id:19, nameTag:'Animal'},
    {id:20, nameTag:'Food'},

];;