export const Work =[  
    {id: 1,author:'user1',img:'/images/1.jpg',like:1256,price:'12',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Sad girl ?'},
    {id: 2,author:'user1',img:'/images/2.jpg',like:1556,price:'10',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Food world'},
    {id: 3,author:'user1',img:'/images/3.jpg',like:2556,price:'11',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'magical girl'},
    {id: 4,author:'user1',img:'/images/4.jpg',like:1586,price:'15',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Medusa mythology'},
    {id: 5,author:'user1',img:'/images/5.jpg',like:756,price:'22',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Flower Queen'},
    {id: 6,author:'user1',img:'/images/6.jpg',like:3523,price:'30',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'The fox slept soundly'},
    {id: 7,author:'user1',img:'/images/7.jpg',like:1856,price:'17',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'flower pot in the morning sun'},
    {id: 8,author:'user1',img:'/images/8.jpg',like:2456,price:'12',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'green forest flower'},
    {id: 9,author:'user1',img:'/images/9.jpg',like:857,price:'10',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Cats and Flowers'},
    {id: 10,author:'user1',img:'/images/10.jpg',like:2566,price:'8',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'cat welcomes the sun'},
    {id: 11,author:'user1',img:'/images/11.jpg',like:1226,price:'11',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'The Girl and flowers'},
    {id: 12,author:'user1',img:'/images/12.jpg',like:1626,price:'9',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Afternoon'},
    {id: 13,author:'user1',img:'/images/13.jpg',like:2586,price:'9',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Food world'},
    {id: 14,author:'user1',img:'/images/14.jpg',like:796,price:'25',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Food world'},
    {id: 15,author:'user1',img:'/images/15.jpg',like:4250,price:'22',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Food world'},
    {id: 16,author:'user1',img:'/images/16.jpg',like:1100,price:'32',avatar:'/images/7.jpg',namework:'beautiful',description:"This is a beautiful painting and it took me quite a while to complete it. If you like, please like me and don't forget to comment!",namework:'Food world'},

 ];;